@ep=http://localhost:8080
@host=localhost:8080

GET /api/ping/
Host: {{host}}
###

POST /web/addRecord.route
Host: {{host}}
Content-Type: application/x-www-form-urlencoded

text=submitting from from rest client does not require quotes